### ISSUE TITLE
[off-topic] Why delete the fingerprint in the Dockerfile?

### ISSUE THREAD

**Issue by lamafab** [vbrandl/yagcdn#75]
Hello

I apologize for asking such an off-topic question here, but I've been debugging an issue for my project for hours and your repository's Dockerfile was my savior. So maybe you don't mind me asking this.

The solution to my problem was this single line (from your Dockerfile):

```dockerfile
RUN rm -r ./target/x86_64-unknown-linux-musl/release/.fingerprint/yagcdn*
```

In my initial Dockerfile, I tried to implement the building step like this:

```dockerfile

FROM rust:1.46.0 AS builder

WORKDIR /app

COPY Cargo.lock Cargo.lock
COPY Cargo.toml Cargo.toml

RUN mkdir -p src/bin
RUN touch src/lib.rs
RUN echo "fn main() {println!(\"if you see this, the build broke\")}" > src/bin/my_bin.rs

RUN cargo build --release

RUN cargo clean -p my-bin
# FIX:
# RUN rm -rf target/release/.fingerprint/my-bin-*

COPY . .

RUN cargo build --release
```

However, for some reason it never re-compiles the `my-bin` package, even after cleaning the package and moving the new files to the container (`COPY . .`). When running the docker image, I just got the `"if you see this, the build broke"` message. Do you know **why** the fingerprint must be deleted and why `cargo clean -p my-bin` does not take care of this? This is just confusing to me, since I never had to do this directly when writing/compiling Rust.

Thank a lot!

**Comment by vbrandl** [comment]
I cannot say exactly why, since I did not look into the `cargo` source code but I saw the same behavior you describe.
I figured, `cargo` might behave somewhat like `make` and check if `last_modified(target/release/.fingerprint...) < last_modified(anything in ./src)` to determine if it needs to rebuild the code at all.

So you build the code for the first time to populate the caching layer, which produces a fingerprint file with a last modified date of `now`. Later you copy the actual source files into the image but their last modified dates are definitely less than `now`. Therefore `cargo` will skip the compilation since it thinks everything is up to date.

Deleting the fingerprint file was the easiest way to invalidate that cache and trigger a build of the actual sources.

**Comment by lamafab** [comment]
Yes, your explanation makes sense. Thanks for the response. I still think that `cargo clean` should have handled this though ¯\\\_(ツ)\_/¯

**Comment by vbrandl** [comment]
Yeah I'm with you on that. But this solution worked for me, so I'm sticking with it :)

**Comment by vbrandl** [comment]
I also found [`cargo-chef`](https://github.com/LukeMathWalker/cargo-chef) which seems to do exactly what I'm doing by hand.

In another project, I use build dependencies for HTML templates and to include version information at build time. There I [have to get dirty](https://github.com/vbrandl/hoc/blob/master/Dockerfile#L9) and remove the build dependencies from my `Cargo.toml` in the first step for the caching to work (this results in the build dependencies not being cached).

`cargo-chef` might solve problems like this.
